#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 102
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 57
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 13

enum {
  sym__whitespace = 1,
  sym_identifier = 2,
  sym_integer = 3,
  sym_floating_point = 4,
  anon_sym_AT = 5,
  sym_duration = 6,
  anon_sym_STAR = 7,
  anon_sym_SEMI = 8,
  anon_sym__ = 9,
  anon_sym_DOLLAR_DOLLAR = 10,
  sym_eqtex_text = 11,
  sym_eqtex_number = 12,
  anon_sym_CARET = 13,
  anon_sym_LBRACE = 14,
  anon_sym_RBRACE = 15,
  anon_sym_DASH = 16,
  anon_sym_PLUS = 17,
  anon_sym_BSLASHfrac = 18,
  anon_sym_BSLASHsqrt = 19,
  anon_sym_BSLASHroot = 20,
  anon_sym_LPAREN = 21,
  anon_sym_RPAREN = 22,
  anon_sym_LBRACK = 23,
  anon_sym_RBRACK = 24,
  anon_sym_EQ = 25,
  sym_comment = 26,
  sym_eol = 27,
  sym__newline = 28,
  sym_source_file = 29,
  sym__statement = 30,
  sym__number = 31,
  sym_enum_value = 32,
  sym_variable = 33,
  sym_command = 34,
  sym_environment_command = 35,
  sym__argument = 36,
  sym_eqtex = 37,
  sym_eqtex_symbol = 38,
  sym_eqtex_power = 39,
  sym__eqtex_powerable = 40,
  sym_eqtex_product = 41,
  sym__eqtex_productable = 42,
  sym_eqtex_opposite = 43,
  sym__eqtex_oppositable = 44,
  sym_eqtex_sum = 45,
  sym_eqtex_fraction = 46,
  sym_eqtex_root = 47,
  sym_eqtex_brackets = 48,
  sym_eqtex_equations = 49,
  sym__eqtex_equationable = 50,
  sym__eqtex_expression = 51,
  aux_sym_source_file_repeat1 = 52,
  aux_sym_command_repeat1 = 53,
  aux_sym_eqtex_product_repeat1 = 54,
  aux_sym_eqtex_sum_repeat1 = 55,
  aux_sym_eqtex_equations_repeat1 = 56,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__whitespace] = "_whitespace",
  [sym_identifier] = "identifier",
  [sym_integer] = "integer",
  [sym_floating_point] = "floating_point",
  [anon_sym_AT] = "@",
  [sym_duration] = "duration",
  [anon_sym_STAR] = "*",
  [anon_sym_SEMI] = ";",
  [anon_sym__] = "_",
  [anon_sym_DOLLAR_DOLLAR] = "$$",
  [sym_eqtex_text] = "eqtex_text",
  [sym_eqtex_number] = "eqtex_number",
  [anon_sym_CARET] = "^",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [anon_sym_BSLASHfrac] = "\\frac",
  [anon_sym_BSLASHsqrt] = "\\sqrt",
  [anon_sym_BSLASHroot] = "\\root",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_EQ] = "=",
  [sym_comment] = "comment",
  [sym_eol] = "eol",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym__number] = "_number",
  [sym_enum_value] = "enum_value",
  [sym_variable] = "variable",
  [sym_command] = "command",
  [sym_environment_command] = "environment_command",
  [sym__argument] = "_argument",
  [sym_eqtex] = "eqtex",
  [sym_eqtex_symbol] = "eqtex_symbol",
  [sym_eqtex_power] = "eqtex_power",
  [sym__eqtex_powerable] = "_eqtex_powerable",
  [sym_eqtex_product] = "eqtex_product",
  [sym__eqtex_productable] = "_eqtex_productable",
  [sym_eqtex_opposite] = "eqtex_opposite",
  [sym__eqtex_oppositable] = "_eqtex_oppositable",
  [sym_eqtex_sum] = "eqtex_sum",
  [sym_eqtex_fraction] = "eqtex_fraction",
  [sym_eqtex_root] = "eqtex_root",
  [sym_eqtex_brackets] = "eqtex_brackets",
  [sym_eqtex_equations] = "eqtex_equations",
  [sym__eqtex_equationable] = "_eqtex_equationable",
  [sym__eqtex_expression] = "_eqtex_expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_command_repeat1] = "command_repeat1",
  [aux_sym_eqtex_product_repeat1] = "eqtex_product_repeat1",
  [aux_sym_eqtex_sum_repeat1] = "eqtex_sum_repeat1",
  [aux_sym_eqtex_equations_repeat1] = "eqtex_equations_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__whitespace] = sym__whitespace,
  [sym_identifier] = sym_identifier,
  [sym_integer] = sym_integer,
  [sym_floating_point] = sym_floating_point,
  [anon_sym_AT] = anon_sym_AT,
  [sym_duration] = sym_duration,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym__] = anon_sym__,
  [anon_sym_DOLLAR_DOLLAR] = anon_sym_DOLLAR_DOLLAR,
  [sym_eqtex_text] = sym_eqtex_text,
  [sym_eqtex_number] = sym_eqtex_number,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_BSLASHfrac] = anon_sym_BSLASHfrac,
  [anon_sym_BSLASHsqrt] = anon_sym_BSLASHsqrt,
  [anon_sym_BSLASHroot] = anon_sym_BSLASHroot,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_comment] = sym_comment,
  [sym_eol] = sym_eol,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym__number] = sym__number,
  [sym_enum_value] = sym_enum_value,
  [sym_variable] = sym_variable,
  [sym_command] = sym_command,
  [sym_environment_command] = sym_environment_command,
  [sym__argument] = sym__argument,
  [sym_eqtex] = sym_eqtex,
  [sym_eqtex_symbol] = sym_eqtex_symbol,
  [sym_eqtex_power] = sym_eqtex_power,
  [sym__eqtex_powerable] = sym__eqtex_powerable,
  [sym_eqtex_product] = sym_eqtex_product,
  [sym__eqtex_productable] = sym__eqtex_productable,
  [sym_eqtex_opposite] = sym_eqtex_opposite,
  [sym__eqtex_oppositable] = sym__eqtex_oppositable,
  [sym_eqtex_sum] = sym_eqtex_sum,
  [sym_eqtex_fraction] = sym_eqtex_fraction,
  [sym_eqtex_root] = sym_eqtex_root,
  [sym_eqtex_brackets] = sym_eqtex_brackets,
  [sym_eqtex_equations] = sym_eqtex_equations,
  [sym__eqtex_equationable] = sym__eqtex_equationable,
  [sym__eqtex_expression] = sym__eqtex_expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_command_repeat1] = aux_sym_command_repeat1,
  [aux_sym_eqtex_product_repeat1] = aux_sym_eqtex_product_repeat1,
  [aux_sym_eqtex_sum_repeat1] = aux_sym_eqtex_sum_repeat1,
  [aux_sym_eqtex_equations_repeat1] = aux_sym_eqtex_equations_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__whitespace] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_floating_point] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_duration] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_eqtex_text] = {
    .visible = true,
    .named = true,
  },
  [sym_eqtex_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHfrac] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHsqrt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHroot] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_eol] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__number] = {
    .visible = false,
    .named = true,
  },
  [sym_enum_value] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_environment_command] = {
    .visible = true,
    .named = true,
  },
  [sym__argument] = {
    .visible = false,
    .named = true,
  },
  [sym_eqtex] = {
    .visible = true,
    .named = true,
  },
  [sym_eqtex_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_eqtex_power] = {
    .visible = true,
    .named = true,
  },
  [sym__eqtex_powerable] = {
    .visible = false,
    .named = true,
  },
  [sym_eqtex_product] = {
    .visible = true,
    .named = true,
  },
  [sym__eqtex_productable] = {
    .visible = false,
    .named = true,
  },
  [sym_eqtex_opposite] = {
    .visible = true,
    .named = true,
  },
  [sym__eqtex_oppositable] = {
    .visible = false,
    .named = true,
  },
  [sym_eqtex_sum] = {
    .visible = true,
    .named = true,
  },
  [sym_eqtex_fraction] = {
    .visible = true,
    .named = true,
  },
  [sym_eqtex_root] = {
    .visible = true,
    .named = true,
  },
  [sym_eqtex_brackets] = {
    .visible = true,
    .named = true,
  },
  [sym_eqtex_equations] = {
    .visible = true,
    .named = true,
  },
  [sym__eqtex_equationable] = {
    .visible = false,
    .named = true,
  },
  [sym__eqtex_expression] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_command_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_eqtex_product_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_eqtex_sum_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_eqtex_equations_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_argument = 1,
  field_duration = 2,
  field_id = 3,
  field_runtime = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_duration] = "duration",
  [field_id] = "id",
  [field_runtime] = "runtime",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 2},
  [9] = {.index = 13, .length = 3},
  [10] = {.index = 16, .length = 3},
  [11] = {.index = 19, .length = 3},
  [12] = {.index = 22, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_id, 0},
  [1] =
    {field_argument, 0},
  [2] =
    {field_id, 1},
  [3] =
    {field_duration, 1},
    {field_id, 0},
  [5] =
    {field_argument, 2, .inherited = true},
    {field_id, 0},
  [7] =
    {field_argument, 0, .inherited = true},
    {field_argument, 1, .inherited = true},
  [9] =
    {field_id, 0},
    {field_runtime, 1},
  [11] =
    {field_argument, 2, .inherited = true},
    {field_id, 1},
  [13] =
    {field_argument, 3, .inherited = true},
    {field_duration, 1},
    {field_id, 0},
  [16] =
    {field_duration, 1},
    {field_id, 0},
    {field_runtime, 2},
  [19] =
    {field_argument, 3, .inherited = true},
    {field_id, 0},
    {field_runtime, 1},
  [22] =
    {field_argument, 4, .inherited = true},
    {field_duration, 1},
    {field_id, 0},
    {field_runtime, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 48,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 80,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(25);
      if (lookahead == '$') ADVANCE(2);
      if (lookahead == '(') ADVANCE(58);
      if (lookahead == ')') ADVANCE(59);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '+') ADVANCE(54);
      if (lookahead == '-') ADVANCE(53);
      if (lookahead == ';') ADVANCE(41);
      if (lookahead == '=') ADVANCE(62);
      if (lookahead == '@') ADVANCE(34);
      if (lookahead == '[') ADVANCE(60);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead == ']') ADVANCE(61);
      if (lookahead == '^') ADVANCE(49);
      if (lookahead == '_') ADVANCE(42);
      if (lookahead == '{') ADVANCE(50);
      if (lookahead == '}') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 1:
      if (lookahead == '$') ADVANCE(2);
      if (lookahead == '(') ADVANCE(58);
      if (lookahead == ')') ADVANCE(59);
      if (lookahead == '+') ADVANCE(54);
      if (lookahead == '-') ADVANCE(53);
      if (lookahead == '=') ADVANCE(62);
      if (lookahead == '[') ADVANCE(60);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead == ']') ADVANCE(61);
      if (lookahead == '^') ADVANCE(49);
      if (lookahead == '}') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 2:
      if (lookahead == '$') ADVANCE(43);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == ';') ADVANCE(41);
      if (lookahead == '@') ADVANCE(34);
      if (lookahead == '[') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(5);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '[') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 6:
      if (lookahead == ']') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(55);
      END_STATE();
    case 9:
      if (lookahead == 'f') ADVANCE(14);
      if (lookahead == 'r') ADVANCE(12);
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'm') ADVANCE(36);
      if (lookahead == 's') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 13:
      if (lookahead == 'q') ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 15:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 18:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 19:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 24:
      if (eof) ADVANCE(25);
      if (lookahead == '$') ADVANCE(2);
      if (lookahead == ')') ADVANCE(59);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '+') ADVANCE(54);
      if (lookahead == '-') ADVANCE(52);
      if (lookahead == ';') ADVANCE(41);
      if (lookahead == '=') ADVANCE(62);
      if (lookahead == ']') ADVANCE(61);
      if (lookahead == '_') ADVANCE(42);
      if (lookahead == '}') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym__whitespace);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_floating_point);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == 'm') ADVANCE(36);
      if (lookahead == 's') ADVANCE(38);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_floating_point);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_floating_point);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_floating_point);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_duration);
      if (lookahead == '_') ADVANCE(39);
      if (lookahead == 's') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_duration);
      if (lookahead == '_') ADVANCE(39);
      if (lookahead == 's') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_duration);
      if (lookahead == '_') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_duration);
      if (lookahead == '_') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_duration);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DOLLAR_DOLLAR);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_eqtex_text);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_eqtex_number);
      if (lookahead == 'm') ADVANCE(35);
      if (lookahead == 's') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_eqtex_number);
      if (lookahead == 'm') ADVANCE(36);
      if (lookahead == 's') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_eqtex_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_eqtex_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_BSLASHfrac);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_BSLASHsqrt);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_BSLASHroot);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 24, .external_lex_state = 2},
  [2] = {.lex_state = 1, .external_lex_state = 2},
  [3] = {.lex_state = 1, .external_lex_state = 2},
  [4] = {.lex_state = 1, .external_lex_state = 2},
  [5] = {.lex_state = 1, .external_lex_state = 2},
  [6] = {.lex_state = 1, .external_lex_state = 2},
  [7] = {.lex_state = 1, .external_lex_state = 2},
  [8] = {.lex_state = 1, .external_lex_state = 2},
  [9] = {.lex_state = 1, .external_lex_state = 2},
  [10] = {.lex_state = 1, .external_lex_state = 2},
  [11] = {.lex_state = 1, .external_lex_state = 2},
  [12] = {.lex_state = 1, .external_lex_state = 2},
  [13] = {.lex_state = 1, .external_lex_state = 2},
  [14] = {.lex_state = 1, .external_lex_state = 2},
  [15] = {.lex_state = 1, .external_lex_state = 2},
  [16] = {.lex_state = 1, .external_lex_state = 2},
  [17] = {.lex_state = 1, .external_lex_state = 2},
  [18] = {.lex_state = 1, .external_lex_state = 2},
  [19] = {.lex_state = 1, .external_lex_state = 2},
  [20] = {.lex_state = 1, .external_lex_state = 2},
  [21] = {.lex_state = 1, .external_lex_state = 2},
  [22] = {.lex_state = 1, .external_lex_state = 2},
  [23] = {.lex_state = 1, .external_lex_state = 2},
  [24] = {.lex_state = 1, .external_lex_state = 2},
  [25] = {.lex_state = 1, .external_lex_state = 2},
  [26] = {.lex_state = 1, .external_lex_state = 2},
  [27] = {.lex_state = 1, .external_lex_state = 2},
  [28] = {.lex_state = 1, .external_lex_state = 2},
  [29] = {.lex_state = 1, .external_lex_state = 2},
  [30] = {.lex_state = 3, .external_lex_state = 3},
  [31] = {.lex_state = 3, .external_lex_state = 3},
  [32] = {.lex_state = 3, .external_lex_state = 3},
  [33] = {.lex_state = 3, .external_lex_state = 3},
  [34] = {.lex_state = 3, .external_lex_state = 3},
  [35] = {.lex_state = 3, .external_lex_state = 3},
  [36] = {.lex_state = 3, .external_lex_state = 3},
  [37] = {.lex_state = 3, .external_lex_state = 3},
  [38] = {.lex_state = 3, .external_lex_state = 3},
  [39] = {.lex_state = 3, .external_lex_state = 3},
  [40] = {.lex_state = 3, .external_lex_state = 3},
  [41] = {.lex_state = 24, .external_lex_state = 2},
  [42] = {.lex_state = 24, .external_lex_state = 2},
  [43] = {.lex_state = 24, .external_lex_state = 2},
  [44] = {.lex_state = 24, .external_lex_state = 2},
  [45] = {.lex_state = 24, .external_lex_state = 2},
  [46] = {.lex_state = 24, .external_lex_state = 2},
  [47] = {.lex_state = 3, .external_lex_state = 3},
  [48] = {.lex_state = 3, .external_lex_state = 3},
  [49] = {.lex_state = 24, .external_lex_state = 2},
  [50] = {.lex_state = 24, .external_lex_state = 2},
  [51] = {.lex_state = 24, .external_lex_state = 2},
  [52] = {.lex_state = 3, .external_lex_state = 3},
  [53] = {.lex_state = 24, .external_lex_state = 2},
  [54] = {.lex_state = 0, .external_lex_state = 2},
  [55] = {.lex_state = 0, .external_lex_state = 2},
  [56] = {.lex_state = 0, .external_lex_state = 2},
  [57] = {.lex_state = 0, .external_lex_state = 2},
  [58] = {.lex_state = 24, .external_lex_state = 2},
  [59] = {.lex_state = 24, .external_lex_state = 2},
  [60] = {.lex_state = 24, .external_lex_state = 2},
  [61] = {.lex_state = 24, .external_lex_state = 2},
  [62] = {.lex_state = 24, .external_lex_state = 2},
  [63] = {.lex_state = 24, .external_lex_state = 2},
  [64] = {.lex_state = 24, .external_lex_state = 2},
  [65] = {.lex_state = 24, .external_lex_state = 2},
  [66] = {.lex_state = 24, .external_lex_state = 2},
  [67] = {.lex_state = 24, .external_lex_state = 2},
  [68] = {.lex_state = 24, .external_lex_state = 2},
  [69] = {.lex_state = 24, .external_lex_state = 2},
  [70] = {.lex_state = 24, .external_lex_state = 2},
  [71] = {.lex_state = 24, .external_lex_state = 2},
  [72] = {.lex_state = 24, .external_lex_state = 2},
  [73] = {.lex_state = 24, .external_lex_state = 2},
  [74] = {.lex_state = 24, .external_lex_state = 2},
  [75] = {.lex_state = 24, .external_lex_state = 2},
  [76] = {.lex_state = 0, .external_lex_state = 2},
  [77] = {.lex_state = 0, .external_lex_state = 2},
  [78] = {.lex_state = 24, .external_lex_state = 2},
  [79] = {.lex_state = 0, .external_lex_state = 2},
  [80] = {.lex_state = 24, .external_lex_state = 2},
  [81] = {.lex_state = 0, .external_lex_state = 2},
  [82] = {.lex_state = 0, .external_lex_state = 2},
  [83] = {.lex_state = 0, .external_lex_state = 2},
  [84] = {.lex_state = 0, .external_lex_state = 2},
  [85] = {.lex_state = 0, .external_lex_state = 2},
  [86] = {.lex_state = 0, .external_lex_state = 2},
  [87] = {.lex_state = 0, .external_lex_state = 2},
  [88] = {.lex_state = 0, .external_lex_state = 2},
  [89] = {.lex_state = 0, .external_lex_state = 2},
  [90] = {.lex_state = 0, .external_lex_state = 2},
  [91] = {.lex_state = 0, .external_lex_state = 2},
  [92] = {.lex_state = 0, .external_lex_state = 2},
  [93] = {.lex_state = 0, .external_lex_state = 2},
  [94] = {.lex_state = 0, .external_lex_state = 2},
  [95] = {.lex_state = 0, .external_lex_state = 2},
  [96] = {.lex_state = 0, .external_lex_state = 2},
  [97] = {.lex_state = 0, .external_lex_state = 2},
  [98] = {.lex_state = 0, .external_lex_state = 2},
  [99] = {.lex_state = 24, .external_lex_state = 2},
  [100] = {.lex_state = 0, .external_lex_state = 2},
  [101] = {.lex_state = 24, .external_lex_state = 2},
};

enum {
  ts_external_token_comment = 0,
  ts_external_token_eol = 1,
  ts_external_token__newline = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_comment] = sym_comment,
  [ts_external_token_eol] = sym_eol,
  [ts_external_token__newline] = sym__newline,
};

static const bool ts_external_scanner_states[4][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_comment] = true,
    [ts_external_token_eol] = true,
    [ts_external_token__newline] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
  },
  [3] = {
    [ts_external_token_eol] = true,
    [ts_external_token__newline] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__whitespace] = ACTIONS(3),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [sym_duration] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_DOLLAR_DOLLAR] = ACTIONS(1),
    [sym_eqtex_text] = ACTIONS(1),
    [sym_eqtex_number] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_BSLASHfrac] = ACTIONS(1),
    [anon_sym_BSLASHsqrt] = ACTIONS(1),
    [anon_sym_BSLASHroot] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_eol] = ACTIONS(1),
    [sym__newline] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(94),
    [sym__statement] = STATE(41),
    [sym_command] = STATE(41),
    [sym_environment_command] = STATE(41),
    [sym_eqtex] = STATE(41),
    [aux_sym_source_file_repeat1] = STATE(41),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym__whitespace] = ACTIONS(3),
    [sym_identifier] = ACTIONS(7),
    [anon_sym__] = ACTIONS(9),
    [anon_sym_DOLLAR_DOLLAR] = ACTIONS(11),
    [sym__newline] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 18,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_BSLASHfrac,
    ACTIONS(19), 1,
      anon_sym_BSLASHsqrt,
    ACTIONS(21), 1,
      anon_sym_BSLASHroot,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(23), 1,
      sym__eqtex_productable,
    STATE(46), 1,
      sym_eqtex_opposite,
    STATE(53), 1,
      sym_eqtex_product,
    STATE(57), 1,
      sym_eqtex_sum,
    STATE(63), 1,
      sym__eqtex_oppositable,
    STATE(77), 1,
      sym__eqtex_equationable,
    STATE(100), 1,
      sym__eqtex_powerable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(13), 2,
      sym_eqtex_text,
      sym_eqtex_number,
    STATE(26), 2,
      sym_eqtex_power,
      sym_eqtex_fraction,
    STATE(81), 2,
      sym_eqtex_equations,
      sym__eqtex_expression,
    STATE(19), 3,
      sym_eqtex_symbol,
      sym_eqtex_root,
      sym_eqtex_brackets,
  [61] = 12,
    ACTIONS(17), 1,
      anon_sym_BSLASHfrac,
    ACTIONS(19), 1,
      anon_sym_BSLASHsqrt,
    ACTIONS(21), 1,
      anon_sym_BSLASHroot,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_DASH,
    STATE(100), 1,
      sym__eqtex_powerable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(13), 2,
      sym_eqtex_text,
      sym_eqtex_number,
    STATE(24), 3,
      sym_eqtex_symbol,
      sym_eqtex_root,
      sym_eqtex_brackets,
    STATE(9), 4,
      sym_eqtex_power,
      sym__eqtex_productable,
      sym_eqtex_fraction,
      aux_sym_eqtex_product_repeat1,
    ACTIONS(27), 6,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [110] = 18,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_BSLASHfrac,
    ACTIONS(19), 1,
      anon_sym_BSLASHsqrt,
    ACTIONS(21), 1,
      anon_sym_BSLASHroot,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(23), 1,
      sym__eqtex_productable,
    STATE(46), 1,
      sym_eqtex_opposite,
    STATE(53), 1,
      sym_eqtex_product,
    STATE(57), 1,
      sym_eqtex_sum,
    STATE(63), 1,
      sym__eqtex_oppositable,
    STATE(77), 1,
      sym__eqtex_equationable,
    STATE(100), 1,
      sym__eqtex_powerable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(13), 2,
      sym_eqtex_text,
      sym_eqtex_number,
    STATE(26), 2,
      sym_eqtex_power,
      sym_eqtex_fraction,
    STATE(97), 2,
      sym_eqtex_equations,
      sym__eqtex_expression,
    STATE(19), 3,
      sym_eqtex_symbol,
      sym_eqtex_root,
      sym_eqtex_brackets,
  [171] = 18,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_BSLASHfrac,
    ACTIONS(19), 1,
      anon_sym_BSLASHsqrt,
    ACTIONS(21), 1,
      anon_sym_BSLASHroot,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(23), 1,
      sym__eqtex_productable,
    STATE(46), 1,
      sym_eqtex_opposite,
    STATE(53), 1,
      sym_eqtex_product,
    STATE(57), 1,
      sym_eqtex_sum,
    STATE(63), 1,
      sym__eqtex_oppositable,
    STATE(77), 1,
      sym__eqtex_equationable,
    STATE(100), 1,
      sym__eqtex_powerable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(13), 2,
      sym_eqtex_text,
      sym_eqtex_number,
    STATE(26), 2,
      sym_eqtex_power,
      sym_eqtex_fraction,
    STATE(95), 2,
      sym_eqtex_equations,
      sym__eqtex_expression,
    STATE(19), 3,
      sym_eqtex_symbol,
      sym_eqtex_root,
      sym_eqtex_brackets,
  [232] = 18,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_BSLASHfrac,
    ACTIONS(19), 1,
      anon_sym_BSLASHsqrt,
    ACTIONS(21), 1,
      anon_sym_BSLASHroot,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(23), 1,
      sym__eqtex_productable,
    STATE(46), 1,
      sym_eqtex_opposite,
    STATE(53), 1,
      sym_eqtex_product,
    STATE(57), 1,
      sym_eqtex_sum,
    STATE(63), 1,
      sym__eqtex_oppositable,
    STATE(77), 1,
      sym__eqtex_equationable,
    STATE(100), 1,
      sym__eqtex_powerable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(13), 2,
      sym_eqtex_text,
      sym_eqtex_number,
    STATE(26), 2,
      sym_eqtex_power,
      sym_eqtex_fraction,
    STATE(96), 2,
      sym_eqtex_equations,
      sym__eqtex_expression,
    STATE(19), 3,
      sym_eqtex_symbol,
      sym_eqtex_root,
      sym_eqtex_brackets,
  [293] = 18,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_BSLASHfrac,
    ACTIONS(19), 1,
      anon_sym_BSLASHsqrt,
    ACTIONS(21), 1,
      anon_sym_BSLASHroot,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(23), 1,
      sym__eqtex_productable,
    STATE(46), 1,
      sym_eqtex_opposite,
    STATE(53), 1,
      sym_eqtex_product,
    STATE(57), 1,
      sym_eqtex_sum,
    STATE(63), 1,
      sym__eqtex_oppositable,
    STATE(77), 1,
      sym__eqtex_equationable,
    STATE(100), 1,
      sym__eqtex_powerable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(13), 2,
      sym_eqtex_text,
      sym_eqtex_number,
    STATE(26), 2,
      sym_eqtex_power,
      sym_eqtex_fraction,
    STATE(98), 2,
      sym_eqtex_equations,
      sym__eqtex_expression,
    STATE(19), 3,
      sym_eqtex_symbol,
      sym_eqtex_root,
      sym_eqtex_brackets,
  [354] = 18,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_BSLASHfrac,
    ACTIONS(19), 1,
      anon_sym_BSLASHsqrt,
    ACTIONS(21), 1,
      anon_sym_BSLASHroot,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(23), 1,
      sym__eqtex_productable,
    STATE(46), 1,
      sym_eqtex_opposite,
    STATE(53), 1,
      sym_eqtex_product,
    STATE(57), 1,
      sym_eqtex_sum,
    STATE(63), 1,
      sym__eqtex_oppositable,
    STATE(77), 1,
      sym__eqtex_equationable,
    STATE(100), 1,
      sym__eqtex_powerable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(13), 2,
      sym_eqtex_text,
      sym_eqtex_number,
    STATE(26), 2,
      sym_eqtex_power,
      sym_eqtex_fraction,
    STATE(91), 2,
      sym_eqtex_equations,
      sym__eqtex_expression,
    STATE(19), 3,
      sym_eqtex_symbol,
      sym_eqtex_root,
      sym_eqtex_brackets,
  [415] = 12,
    ACTIONS(36), 1,
      anon_sym_DASH,
    ACTIONS(38), 1,
      anon_sym_BSLASHfrac,
    ACTIONS(41), 1,
      anon_sym_BSLASHsqrt,
    ACTIONS(44), 1,
      anon_sym_BSLASHroot,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    STATE(100), 1,
      sym__eqtex_powerable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(33), 2,
      sym_eqtex_text,
      sym_eqtex_number,
    STATE(24), 3,
      sym_eqtex_symbol,
      sym_eqtex_root,
      sym_eqtex_brackets,
    STATE(9), 4,
      sym_eqtex_power,
      sym__eqtex_productable,
      sym_eqtex_fraction,
      aux_sym_eqtex_product_repeat1,
    ACTIONS(31), 6,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [464] = 18,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_BSLASHfrac,
    ACTIONS(19), 1,
      anon_sym_BSLASHsqrt,
    ACTIONS(21), 1,
      anon_sym_BSLASHroot,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(23), 1,
      sym__eqtex_productable,
    STATE(46), 1,
      sym_eqtex_opposite,
    STATE(53), 1,
      sym_eqtex_product,
    STATE(57), 1,
      sym_eqtex_sum,
    STATE(63), 1,
      sym__eqtex_oppositable,
    STATE(77), 1,
      sym__eqtex_equationable,
    STATE(100), 1,
      sym__eqtex_powerable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(13), 2,
      sym_eqtex_text,
      sym_eqtex_number,
    STATE(26), 2,
      sym_eqtex_power,
      sym_eqtex_fraction,
    STATE(90), 2,
      sym_eqtex_equations,
      sym__eqtex_expression,
    STATE(19), 3,
      sym_eqtex_symbol,
      sym_eqtex_root,
      sym_eqtex_brackets,
  [525] = 18,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_BSLASHfrac,
    ACTIONS(19), 1,
      anon_sym_BSLASHsqrt,
    ACTIONS(21), 1,
      anon_sym_BSLASHroot,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(23), 1,
      sym__eqtex_productable,
    STATE(46), 1,
      sym_eqtex_opposite,
    STATE(53), 1,
      sym_eqtex_product,
    STATE(57), 1,
      sym_eqtex_sum,
    STATE(63), 1,
      sym__eqtex_oppositable,
    STATE(77), 1,
      sym__eqtex_equationable,
    STATE(100), 1,
      sym__eqtex_powerable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(13), 2,
      sym_eqtex_text,
      sym_eqtex_number,
    STATE(26), 2,
      sym_eqtex_power,
      sym_eqtex_fraction,
    STATE(89), 2,
      sym_eqtex_equations,
      sym__eqtex_expression,
    STATE(19), 3,
      sym_eqtex_symbol,
      sym_eqtex_root,
      sym_eqtex_brackets,
  [586] = 18,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_BSLASHfrac,
    ACTIONS(19), 1,
      anon_sym_BSLASHsqrt,
    ACTIONS(21), 1,
      anon_sym_BSLASHroot,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(23), 1,
      sym__eqtex_productable,
    STATE(46), 1,
      sym_eqtex_opposite,
    STATE(53), 1,
      sym_eqtex_product,
    STATE(57), 1,
      sym_eqtex_sum,
    STATE(63), 1,
      sym__eqtex_oppositable,
    STATE(77), 1,
      sym__eqtex_equationable,
    STATE(100), 1,
      sym__eqtex_powerable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(13), 2,
      sym_eqtex_text,
      sym_eqtex_number,
    STATE(26), 2,
      sym_eqtex_power,
      sym_eqtex_fraction,
    STATE(92), 2,
      sym_eqtex_equations,
      sym__eqtex_expression,
    STATE(19), 3,
      sym_eqtex_symbol,
      sym_eqtex_root,
      sym_eqtex_brackets,
  [647] = 16,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_BSLASHfrac,
    ACTIONS(19), 1,
      anon_sym_BSLASHsqrt,
    ACTIONS(21), 1,
      anon_sym_BSLASHroot,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(23), 1,
      sym__eqtex_productable,
    STATE(42), 1,
      sym_eqtex_opposite,
    STATE(49), 1,
      sym_eqtex_product,
    STATE(63), 1,
      sym__eqtex_oppositable,
    STATE(100), 1,
      sym__eqtex_powerable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(13), 2,
      sym_eqtex_text,
      sym_eqtex_number,
    STATE(25), 2,
      sym_eqtex_power,
      sym_eqtex_fraction,
    STATE(56), 2,
      sym_eqtex_sum,
      sym__eqtex_equationable,
    STATE(22), 3,
      sym_eqtex_symbol,
      sym_eqtex_root,
      sym_eqtex_brackets,
  [702] = 12,
    ACTIONS(17), 1,
      anon_sym_BSLASHfrac,
    ACTIONS(19), 1,
      anon_sym_BSLASHsqrt,
    ACTIONS(21), 1,
      anon_sym_BSLASHroot,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(23), 1,
      sym__eqtex_productable,
    STATE(100), 1,
      sym__eqtex_powerable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(13), 2,
      sym_eqtex_text,
      sym_eqtex_number,
    STATE(29), 2,
      sym_eqtex_power,
      sym_eqtex_fraction,
    STATE(50), 2,
      sym_eqtex_product,
      sym__eqtex_oppositable,
    STATE(21), 3,
      sym_eqtex_symbol,
      sym_eqtex_root,
      sym_eqtex_brackets,
  [745] = 12,
    ACTIONS(17), 1,
      anon_sym_BSLASHfrac,
    ACTIONS(19), 1,
      anon_sym_BSLASHsqrt,
    ACTIONS(21), 1,
      anon_sym_BSLASHroot,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(23), 1,
      sym__eqtex_productable,
    STATE(100), 1,
      sym__eqtex_powerable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(13), 2,
      sym_eqtex_text,
      sym_eqtex_number,
    STATE(29), 2,
      sym_eqtex_power,
      sym_eqtex_fraction,
    STATE(51), 2,
      sym_eqtex_product,
      sym__eqtex_oppositable,
    STATE(21), 3,
      sym_eqtex_symbol,
      sym_eqtex_root,
      sym_eqtex_brackets,
  [788] = 3,
    ACTIONS(55), 1,
      anon_sym_DASH,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(53), 14,
      anon_sym_DOLLAR_DOLLAR,
      sym_eqtex_text,
      sym_eqtex_number,
      anon_sym_CARET,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_BSLASHfrac,
      anon_sym_BSLASHsqrt,
      anon_sym_BSLASHroot,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [812] = 3,
    ACTIONS(59), 1,
      anon_sym_DASH,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(57), 14,
      anon_sym_DOLLAR_DOLLAR,
      sym_eqtex_text,
      sym_eqtex_number,
      anon_sym_CARET,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_BSLASHfrac,
      anon_sym_BSLASHsqrt,
      anon_sym_BSLASHroot,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [836] = 3,
    ACTIONS(63), 1,
      anon_sym_DASH,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(61), 14,
      anon_sym_DOLLAR_DOLLAR,
      sym_eqtex_text,
      sym_eqtex_number,
      anon_sym_CARET,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_BSLASHfrac,
      anon_sym_BSLASHsqrt,
      anon_sym_BSLASHroot,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [860] = 7,
    ACTIONS(69), 1,
      anon_sym_CARET,
    ACTIONS(71), 1,
      anon_sym_DASH,
    ACTIONS(73), 1,
      anon_sym_PLUS,
    ACTIONS(75), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(65), 4,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
    ACTIONS(67), 7,
      sym_eqtex_text,
      sym_eqtex_number,
      anon_sym_BSLASHfrac,
      anon_sym_BSLASHsqrt,
      anon_sym_BSLASHroot,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [892] = 3,
    ACTIONS(79), 1,
      anon_sym_DASH,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(77), 14,
      anon_sym_DOLLAR_DOLLAR,
      sym_eqtex_text,
      sym_eqtex_number,
      anon_sym_CARET,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_BSLASHfrac,
      anon_sym_BSLASHsqrt,
      anon_sym_BSLASHroot,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [916] = 5,
    ACTIONS(69), 1,
      anon_sym_CARET,
    ACTIONS(71), 1,
      anon_sym_DASH,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(73), 6,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
    ACTIONS(67), 7,
      sym_eqtex_text,
      sym_eqtex_number,
      anon_sym_BSLASHfrac,
      anon_sym_BSLASHsqrt,
      anon_sym_BSLASHroot,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [944] = 6,
    ACTIONS(69), 1,
      anon_sym_CARET,
    ACTIONS(71), 1,
      anon_sym_DASH,
    ACTIONS(73), 1,
      anon_sym_PLUS,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(75), 5,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
    ACTIONS(67), 7,
      sym_eqtex_text,
      sym_eqtex_number,
      anon_sym_BSLASHfrac,
      anon_sym_BSLASHsqrt,
      anon_sym_BSLASHroot,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [974] = 10,
    ACTIONS(17), 1,
      anon_sym_BSLASHfrac,
    ACTIONS(19), 1,
      anon_sym_BSLASHsqrt,
    ACTIONS(21), 1,
      anon_sym_BSLASHroot,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(100), 1,
      sym__eqtex_powerable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(13), 2,
      sym_eqtex_text,
      sym_eqtex_number,
    STATE(24), 3,
      sym_eqtex_symbol,
      sym_eqtex_root,
      sym_eqtex_brackets,
    STATE(3), 4,
      sym_eqtex_power,
      sym__eqtex_productable,
      sym_eqtex_fraction,
      aux_sym_eqtex_product_repeat1,
  [1012] = 4,
    ACTIONS(69), 1,
      anon_sym_CARET,
    ACTIONS(81), 1,
      anon_sym_DASH,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(67), 13,
      anon_sym_DOLLAR_DOLLAR,
      sym_eqtex_text,
      sym_eqtex_number,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_BSLASHfrac,
      anon_sym_BSLASHsqrt,
      anon_sym_BSLASHroot,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [1038] = 5,
    ACTIONS(71), 1,
      anon_sym_DASH,
    ACTIONS(73), 1,
      anon_sym_PLUS,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(75), 5,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
    ACTIONS(67), 7,
      sym_eqtex_text,
      sym_eqtex_number,
      anon_sym_BSLASHfrac,
      anon_sym_BSLASHsqrt,
      anon_sym_BSLASHroot,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [1065] = 6,
    ACTIONS(71), 1,
      anon_sym_DASH,
    ACTIONS(73), 1,
      anon_sym_PLUS,
    ACTIONS(75), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(65), 4,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
    ACTIONS(67), 7,
      sym_eqtex_text,
      sym_eqtex_number,
      anon_sym_BSLASHfrac,
      anon_sym_BSLASHsqrt,
      anon_sym_BSLASHroot,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [1094] = 3,
    ACTIONS(85), 1,
      anon_sym_DASH,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(83), 13,
      anon_sym_DOLLAR_DOLLAR,
      sym_eqtex_text,
      sym_eqtex_number,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_BSLASHfrac,
      anon_sym_BSLASHsqrt,
      anon_sym_BSLASHroot,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [1117] = 3,
    ACTIONS(89), 1,
      anon_sym_DASH,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(87), 13,
      anon_sym_DOLLAR_DOLLAR,
      sym_eqtex_text,
      sym_eqtex_number,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_BSLASHfrac,
      anon_sym_BSLASHsqrt,
      anon_sym_BSLASHroot,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [1140] = 4,
    ACTIONS(71), 1,
      anon_sym_DASH,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(73), 6,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
    ACTIONS(67), 7,
      sym_eqtex_text,
      sym_eqtex_number,
      anon_sym_BSLASHfrac,
      anon_sym_BSLASHsqrt,
      anon_sym_BSLASHroot,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [1165] = 9,
    ACTIONS(93), 1,
      sym_floating_point,
    ACTIONS(95), 1,
      anon_sym_AT,
    ACTIONS(97), 1,
      anon_sym_STAR,
    ACTIONS(99), 1,
      anon_sym_SEMI,
    ACTIONS(101), 1,
      sym_eol,
    STATE(32), 1,
      aux_sym_command_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(91), 2,
      sym_integer,
      sym_duration,
    STATE(47), 4,
      sym__number,
      sym_enum_value,
      sym_variable,
      sym__argument,
  [1198] = 9,
    ACTIONS(93), 1,
      sym_floating_point,
    ACTIONS(95), 1,
      anon_sym_AT,
    ACTIONS(97), 1,
      anon_sym_STAR,
    ACTIONS(103), 1,
      anon_sym_SEMI,
    ACTIONS(105), 1,
      sym_eol,
    STATE(32), 1,
      aux_sym_command_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(91), 2,
      sym_integer,
      sym_duration,
    STATE(47), 4,
      sym__number,
      sym_enum_value,
      sym_variable,
      sym__argument,
  [1231] = 8,
    ACTIONS(110), 1,
      sym_floating_point,
    ACTIONS(113), 1,
      anon_sym_AT,
    ACTIONS(116), 1,
      anon_sym_STAR,
    STATE(32), 1,
      aux_sym_command_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(107), 2,
      sym_integer,
      sym_duration,
    ACTIONS(119), 2,
      sym_eol,
      anon_sym_SEMI,
    STATE(47), 4,
      sym__number,
      sym_enum_value,
      sym_variable,
      sym__argument,
  [1262] = 9,
    ACTIONS(93), 1,
      sym_floating_point,
    ACTIONS(95), 1,
      anon_sym_AT,
    ACTIONS(97), 1,
      anon_sym_STAR,
    ACTIONS(121), 1,
      anon_sym_SEMI,
    ACTIONS(123), 1,
      sym_eol,
    STATE(32), 1,
      aux_sym_command_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(91), 2,
      sym_integer,
      sym_duration,
    STATE(47), 4,
      sym__number,
      sym_enum_value,
      sym_variable,
      sym__argument,
  [1295] = 8,
    ACTIONS(93), 1,
      sym_floating_point,
    ACTIONS(95), 1,
      anon_sym_AT,
    ACTIONS(97), 1,
      anon_sym_STAR,
    STATE(39), 1,
      aux_sym_command_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(91), 2,
      sym_integer,
      sym_duration,
    ACTIONS(125), 2,
      sym_eol,
      anon_sym_SEMI,
    STATE(47), 4,
      sym__number,
      sym_enum_value,
      sym_variable,
      sym__argument,
  [1326] = 8,
    ACTIONS(93), 1,
      sym_floating_point,
    ACTIONS(95), 1,
      anon_sym_AT,
    ACTIONS(97), 1,
      anon_sym_STAR,
    STATE(38), 1,
      aux_sym_command_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(91), 2,
      sym_integer,
      sym_duration,
    ACTIONS(127), 2,
      sym_eol,
      anon_sym_SEMI,
    STATE(47), 4,
      sym__number,
      sym_enum_value,
      sym_variable,
      sym__argument,
  [1357] = 8,
    ACTIONS(93), 1,
      sym_floating_point,
    ACTIONS(95), 1,
      anon_sym_AT,
    ACTIONS(97), 1,
      anon_sym_STAR,
    STATE(30), 1,
      aux_sym_command_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(91), 2,
      sym_integer,
      sym_duration,
    ACTIONS(129), 2,
      sym_eol,
      anon_sym_SEMI,
    STATE(47), 4,
      sym__number,
      sym_enum_value,
      sym_variable,
      sym__argument,
  [1388] = 8,
    ACTIONS(93), 1,
      sym_floating_point,
    ACTIONS(95), 1,
      anon_sym_AT,
    ACTIONS(97), 1,
      anon_sym_STAR,
    STATE(31), 1,
      aux_sym_command_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(91), 2,
      sym_integer,
      sym_duration,
    ACTIONS(131), 2,
      sym_eol,
      anon_sym_SEMI,
    STATE(47), 4,
      sym__number,
      sym_enum_value,
      sym_variable,
      sym__argument,
  [1419] = 9,
    ACTIONS(93), 1,
      sym_floating_point,
    ACTIONS(95), 1,
      anon_sym_AT,
    ACTIONS(97), 1,
      anon_sym_STAR,
    ACTIONS(133), 1,
      anon_sym_SEMI,
    ACTIONS(135), 1,
      sym_eol,
    STATE(32), 1,
      aux_sym_command_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(91), 2,
      sym_integer,
      sym_duration,
    STATE(47), 4,
      sym__number,
      sym_enum_value,
      sym_variable,
      sym__argument,
  [1452] = 9,
    ACTIONS(93), 1,
      sym_floating_point,
    ACTIONS(95), 1,
      anon_sym_AT,
    ACTIONS(97), 1,
      anon_sym_STAR,
    ACTIONS(137), 1,
      anon_sym_SEMI,
    ACTIONS(139), 1,
      sym_eol,
    STATE(32), 1,
      aux_sym_command_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(91), 2,
      sym_integer,
      sym_duration,
    STATE(47), 4,
      sym__number,
      sym_enum_value,
      sym_variable,
      sym__argument,
  [1485] = 8,
    ACTIONS(93), 1,
      sym_floating_point,
    ACTIONS(95), 1,
      anon_sym_AT,
    ACTIONS(97), 1,
      anon_sym_STAR,
    STATE(33), 1,
      aux_sym_command_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(91), 2,
      sym_integer,
      sym_duration,
    ACTIONS(141), 2,
      sym_eol,
      anon_sym_SEMI,
    STATE(47), 4,
      sym__number,
      sym_enum_value,
      sym_variable,
      sym__argument,
  [1516] = 6,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym__,
    ACTIONS(11), 1,
      anon_sym_DOLLAR_DOLLAR,
    ACTIONS(143), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    STATE(44), 5,
      sym__statement,
      sym_command,
      sym_environment_command,
      sym_eqtex,
      aux_sym_source_file_repeat1,
  [1540] = 5,
    ACTIONS(145), 1,
      anon_sym_DASH,
    ACTIONS(147), 1,
      anon_sym_PLUS,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    STATE(45), 2,
      sym_eqtex_opposite,
      aux_sym_eqtex_sum_repeat1,
    ACTIONS(75), 5,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [1562] = 5,
    ACTIONS(151), 1,
      anon_sym_DASH,
    ACTIONS(154), 1,
      anon_sym_PLUS,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    STATE(43), 2,
      sym_eqtex_opposite,
      aux_sym_eqtex_sum_repeat1,
    ACTIONS(149), 5,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [1584] = 6,
    ACTIONS(157), 1,
      ts_builtin_sym_end,
    ACTIONS(159), 1,
      sym_identifier,
    ACTIONS(162), 1,
      anon_sym__,
    ACTIONS(165), 1,
      anon_sym_DOLLAR_DOLLAR,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    STATE(44), 5,
      sym__statement,
      sym_command,
      sym_environment_command,
      sym_eqtex,
      aux_sym_source_file_repeat1,
  [1608] = 5,
    ACTIONS(145), 1,
      anon_sym_DASH,
    ACTIONS(147), 1,
      anon_sym_PLUS,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    STATE(43), 2,
      sym_eqtex_opposite,
      aux_sym_eqtex_sum_repeat1,
    ACTIONS(168), 5,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [1630] = 6,
    ACTIONS(75), 1,
      anon_sym_EQ,
    ACTIONS(145), 1,
      anon_sym_DASH,
    ACTIONS(147), 1,
      anon_sym_PLUS,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    STATE(45), 2,
      sym_eqtex_opposite,
      aux_sym_eqtex_sum_repeat1,
    ACTIONS(65), 4,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1654] = 3,
    ACTIONS(172), 1,
      sym_floating_point,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(170), 6,
      sym_eol,
      sym_integer,
      anon_sym_AT,
      sym_duration,
      anon_sym_STAR,
      anon_sym_SEMI,
  [1670] = 3,
    ACTIONS(176), 1,
      sym_floating_point,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(174), 6,
      sym_eol,
      sym_integer,
      anon_sym_AT,
      sym_duration,
      anon_sym_STAR,
      anon_sym_SEMI,
  [1686] = 3,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(73), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(75), 5,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [1702] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(178), 7,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [1716] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(149), 7,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [1730] = 3,
    ACTIONS(182), 1,
      sym_floating_point,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(180), 6,
      sym_eol,
      sym_integer,
      anon_sym_AT,
      sym_duration,
      anon_sym_STAR,
      anon_sym_SEMI,
  [1746] = 4,
    ACTIONS(75), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(73), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(65), 4,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1764] = 4,
    ACTIONS(186), 1,
      anon_sym_EQ,
    STATE(54), 1,
      aux_sym_eqtex_equations_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(184), 4,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1781] = 4,
    ACTIONS(191), 1,
      anon_sym_EQ,
    STATE(54), 1,
      aux_sym_eqtex_equations_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(189), 4,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1798] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(184), 5,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [1810] = 3,
    ACTIONS(75), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(65), 4,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1824] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(193), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1835] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(195), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1846] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(197), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1857] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(199), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1868] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(199), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1879] = 4,
    ACTIONS(145), 1,
      anon_sym_DASH,
    ACTIONS(147), 1,
      anon_sym_PLUS,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    STATE(45), 2,
      sym_eqtex_opposite,
      aux_sym_eqtex_sum_repeat1,
  [1894] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(201), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1905] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(201), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1916] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(203), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1927] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(203), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1938] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(205), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1949] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(205), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1960] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(207), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1971] = 5,
    ACTIONS(209), 1,
      sym_duration,
    ACTIONS(211), 1,
      anon_sym_STAR,
    ACTIONS(213), 1,
      anon_sym_SEMI,
    STATE(85), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [1988] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(215), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1999] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(217), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [2010] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(219), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [2021] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(215), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [2032] = 4,
    ACTIONS(211), 1,
      anon_sym_STAR,
    ACTIONS(221), 1,
      anon_sym_SEMI,
    STATE(93), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [2046] = 3,
    ACTIONS(191), 1,
      anon_sym_EQ,
    STATE(55), 1,
      aux_sym_eqtex_equations_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [2057] = 2,
    ACTIONS(223), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [2065] = 2,
    ACTIONS(225), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [2073] = 2,
    ACTIONS(227), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [2081] = 2,
    ACTIONS(229), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [2089] = 2,
    ACTIONS(231), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [2097] = 2,
    ACTIONS(233), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [2105] = 2,
    ACTIONS(174), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [2113] = 2,
    ACTIONS(235), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [2121] = 2,
    ACTIONS(237), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [2129] = 2,
    ACTIONS(239), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [2137] = 2,
    ACTIONS(241), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [2145] = 2,
    ACTIONS(229), 1,
      anon_sym_RBRACK,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [2153] = 2,
    ACTIONS(243), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [2161] = 2,
    ACTIONS(245), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [2169] = 2,
    ACTIONS(247), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [2177] = 2,
    ACTIONS(249), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [2185] = 2,
    ACTIONS(251), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [2193] = 2,
    ACTIONS(253), 1,
      anon_sym_DOLLAR_DOLLAR,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [2201] = 2,
    ACTIONS(255), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [2209] = 2,
    ACTIONS(257), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [2217] = 2,
    ACTIONS(259), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [2225] = 2,
    ACTIONS(261), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [2233] = 2,
    ACTIONS(263), 1,
      anon_sym_CARET,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [2241] = 2,
    ACTIONS(265), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 61,
  [SMALL_STATE(4)] = 110,
  [SMALL_STATE(5)] = 171,
  [SMALL_STATE(6)] = 232,
  [SMALL_STATE(7)] = 293,
  [SMALL_STATE(8)] = 354,
  [SMALL_STATE(9)] = 415,
  [SMALL_STATE(10)] = 464,
  [SMALL_STATE(11)] = 525,
  [SMALL_STATE(12)] = 586,
  [SMALL_STATE(13)] = 647,
  [SMALL_STATE(14)] = 702,
  [SMALL_STATE(15)] = 745,
  [SMALL_STATE(16)] = 788,
  [SMALL_STATE(17)] = 812,
  [SMALL_STATE(18)] = 836,
  [SMALL_STATE(19)] = 860,
  [SMALL_STATE(20)] = 892,
  [SMALL_STATE(21)] = 916,
  [SMALL_STATE(22)] = 944,
  [SMALL_STATE(23)] = 974,
  [SMALL_STATE(24)] = 1012,
  [SMALL_STATE(25)] = 1038,
  [SMALL_STATE(26)] = 1065,
  [SMALL_STATE(27)] = 1094,
  [SMALL_STATE(28)] = 1117,
  [SMALL_STATE(29)] = 1140,
  [SMALL_STATE(30)] = 1165,
  [SMALL_STATE(31)] = 1198,
  [SMALL_STATE(32)] = 1231,
  [SMALL_STATE(33)] = 1262,
  [SMALL_STATE(34)] = 1295,
  [SMALL_STATE(35)] = 1326,
  [SMALL_STATE(36)] = 1357,
  [SMALL_STATE(37)] = 1388,
  [SMALL_STATE(38)] = 1419,
  [SMALL_STATE(39)] = 1452,
  [SMALL_STATE(40)] = 1485,
  [SMALL_STATE(41)] = 1516,
  [SMALL_STATE(42)] = 1540,
  [SMALL_STATE(43)] = 1562,
  [SMALL_STATE(44)] = 1584,
  [SMALL_STATE(45)] = 1608,
  [SMALL_STATE(46)] = 1630,
  [SMALL_STATE(47)] = 1654,
  [SMALL_STATE(48)] = 1670,
  [SMALL_STATE(49)] = 1686,
  [SMALL_STATE(50)] = 1702,
  [SMALL_STATE(51)] = 1716,
  [SMALL_STATE(52)] = 1730,
  [SMALL_STATE(53)] = 1746,
  [SMALL_STATE(54)] = 1764,
  [SMALL_STATE(55)] = 1781,
  [SMALL_STATE(56)] = 1798,
  [SMALL_STATE(57)] = 1810,
  [SMALL_STATE(58)] = 1824,
  [SMALL_STATE(59)] = 1835,
  [SMALL_STATE(60)] = 1846,
  [SMALL_STATE(61)] = 1857,
  [SMALL_STATE(62)] = 1868,
  [SMALL_STATE(63)] = 1879,
  [SMALL_STATE(64)] = 1894,
  [SMALL_STATE(65)] = 1905,
  [SMALL_STATE(66)] = 1916,
  [SMALL_STATE(67)] = 1927,
  [SMALL_STATE(68)] = 1938,
  [SMALL_STATE(69)] = 1949,
  [SMALL_STATE(70)] = 1960,
  [SMALL_STATE(71)] = 1971,
  [SMALL_STATE(72)] = 1988,
  [SMALL_STATE(73)] = 1999,
  [SMALL_STATE(74)] = 2010,
  [SMALL_STATE(75)] = 2021,
  [SMALL_STATE(76)] = 2032,
  [SMALL_STATE(77)] = 2046,
  [SMALL_STATE(78)] = 2057,
  [SMALL_STATE(79)] = 2065,
  [SMALL_STATE(80)] = 2073,
  [SMALL_STATE(81)] = 2081,
  [SMALL_STATE(82)] = 2089,
  [SMALL_STATE(83)] = 2097,
  [SMALL_STATE(84)] = 2105,
  [SMALL_STATE(85)] = 2113,
  [SMALL_STATE(86)] = 2121,
  [SMALL_STATE(87)] = 2129,
  [SMALL_STATE(88)] = 2137,
  [SMALL_STATE(89)] = 2145,
  [SMALL_STATE(90)] = 2153,
  [SMALL_STATE(91)] = 2161,
  [SMALL_STATE(92)] = 2169,
  [SMALL_STATE(93)] = 2177,
  [SMALL_STATE(94)] = 2185,
  [SMALL_STATE(95)] = 2193,
  [SMALL_STATE(96)] = 2201,
  [SMALL_STATE(97)] = 2209,
  [SMALL_STATE(98)] = 2217,
  [SMALL_STATE(99)] = 2225,
  [SMALL_STATE(100)] = 2233,
  [SMALL_STATE(101)] = 2241,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eqtex_product, 2),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_eqtex_product, 2),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_eqtex_product_repeat1, 2),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_eqtex_product_repeat1, 2), SHIFT_REPEAT(17),
  [36] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_eqtex_product_repeat1, 2),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_eqtex_product_repeat1, 2), SHIFT_REPEAT(88),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_eqtex_product_repeat1, 2), SHIFT_REPEAT(86),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_eqtex_product_repeat1, 2), SHIFT_REPEAT(82),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_eqtex_product_repeat1, 2), SHIFT_REPEAT(2),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_eqtex_product_repeat1, 2), SHIFT_REPEAT(11),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eqtex_root, 4),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_eqtex_root, 4),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eqtex_symbol, 1),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_eqtex_symbol, 1),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eqtex_root, 7),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_eqtex_root, 7),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__eqtex_expression, 1),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__eqtex_productable, 1),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__eqtex_powerable, 1),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__eqtex_oppositable, 1),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__eqtex_oppositable, 1),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__eqtex_equationable, 1),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eqtex_brackets, 3),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_eqtex_brackets, 3),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__eqtex_productable, 1),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eqtex_fraction, 7),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_eqtex_fraction, 7),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eqtex_power, 5),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_eqtex_power, 5),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2, .production_id = 6), SHIFT_REPEAT(47),
  [110] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, .production_id = 6), SHIFT_REPEAT(47),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2, .production_id = 6), SHIFT_REPEAT(78),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2, .production_id = 6), SHIFT_REPEAT(101),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2, .production_id = 6),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_eqtex_sum_repeat1, 2),
  [151] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_eqtex_sum_repeat1, 2), SHIFT_REPEAT(14),
  [154] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_eqtex_sum_repeat1, 2), SHIFT_REPEAT(15),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(71),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(99),
  [165] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(5),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eqtex_sum, 2),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 1, .production_id = 2),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 1, .production_id = 2),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 2),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 2),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eqtex_opposite, 2),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_value, 2),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_enum_value, 2),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_eqtex_equations_repeat1, 2),
  [186] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_eqtex_equations_repeat1, 2), SHIFT_REPEAT(13),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eqtex_equations, 2),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 4, .production_id = 7),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_environment_command, 3, .production_id = 3),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 4, .production_id = 4),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 4, .production_id = 5),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_environment_command, 4, .production_id = 8),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 6, .production_id = 12),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 5, .production_id = 11),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 5, .production_id = 10),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 5, .production_id = 9),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eqtex, 3),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 3, .production_id = 1),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [251] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_eqideo_external_scanner_create(void);
void tree_sitter_eqideo_external_scanner_destroy(void *);
bool tree_sitter_eqideo_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_eqideo_external_scanner_serialize(void *, char *);
void tree_sitter_eqideo_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_eqideo(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_eqideo_external_scanner_create,
      tree_sitter_eqideo_external_scanner_destroy,
      tree_sitter_eqideo_external_scanner_scan,
      tree_sitter_eqideo_external_scanner_serialize,
      tree_sitter_eqideo_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
