#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 84
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 13

enum {
  sym__whitespace = 1,
  sym_identifier = 2,
  sym_integer = 3,
  sym_floating_point = 4,
  anon_sym_AT = 5,
  sym_duration = 6,
  anon_sym_STAR = 7,
  anon_sym_SEMI = 8,
  anon_sym__ = 9,
  anon_sym_DOLLAR_DOLLAR = 10,
  sym_eqtex_text = 11,
  sym_eqtex_number = 12,
  anon_sym_CARET = 13,
  anon_sym_LBRACE = 14,
  anon_sym_RBRACE = 15,
  anon_sym_DASH = 16,
  anon_sym_PLUS = 17,
  anon_sym_LPAREN = 18,
  anon_sym_RPAREN = 19,
  anon_sym_LBRACK = 20,
  anon_sym_RBRACK = 21,
  anon_sym_EQ = 22,
  sym_comment = 23,
  sym_eol = 24,
  sym__newline = 25,
  sym_source_file = 26,
  sym__statement = 27,
  sym__number = 28,
  sym_enum_value = 29,
  sym_variable = 30,
  sym_command = 31,
  sym_environment_command = 32,
  sym__argument = 33,
  sym_eqtex = 34,
  sym_eqtex_symbol = 35,
  sym_eqtex_power = 36,
  sym__eqtex_powerable = 37,
  sym_eqtex_product = 38,
  sym__eqtex_productable = 39,
  sym_eqtex_opposite = 40,
  sym__eqtex_oppositable = 41,
  sym_eqtex_sum = 42,
  sym_eqtex_brackets = 43,
  sym_eqtex_equations = 44,
  sym__eqtex_equationable = 45,
  sym__eqtex_expression = 46,
  aux_sym_source_file_repeat1 = 47,
  aux_sym_command_repeat1 = 48,
  aux_sym_eqtex_product_repeat1 = 49,
  aux_sym_eqtex_sum_repeat1 = 50,
  aux_sym_eqtex_equations_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__whitespace] = "_whitespace",
  [sym_identifier] = "identifier",
  [sym_integer] = "integer",
  [sym_floating_point] = "floating_point",
  [anon_sym_AT] = "@",
  [sym_duration] = "duration",
  [anon_sym_STAR] = "*",
  [anon_sym_SEMI] = ";",
  [anon_sym__] = "_",
  [anon_sym_DOLLAR_DOLLAR] = "$$",
  [sym_eqtex_text] = "eqtex_text",
  [sym_eqtex_number] = "eqtex_number",
  [anon_sym_CARET] = "^",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_EQ] = "=",
  [sym_comment] = "comment",
  [sym_eol] = "eol",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym__number] = "_number",
  [sym_enum_value] = "enum_value",
  [sym_variable] = "variable",
  [sym_command] = "command",
  [sym_environment_command] = "environment_command",
  [sym__argument] = "_argument",
  [sym_eqtex] = "eqtex",
  [sym_eqtex_symbol] = "eqtex_symbol",
  [sym_eqtex_power] = "eqtex_power",
  [sym__eqtex_powerable] = "_eqtex_powerable",
  [sym_eqtex_product] = "eqtex_product",
  [sym__eqtex_productable] = "_eqtex_productable",
  [sym_eqtex_opposite] = "eqtex_opposite",
  [sym__eqtex_oppositable] = "_eqtex_oppositable",
  [sym_eqtex_sum] = "eqtex_sum",
  [sym_eqtex_brackets] = "eqtex_brackets",
  [sym_eqtex_equations] = "eqtex_equations",
  [sym__eqtex_equationable] = "_eqtex_equationable",
  [sym__eqtex_expression] = "_eqtex_expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_command_repeat1] = "command_repeat1",
  [aux_sym_eqtex_product_repeat1] = "eqtex_product_repeat1",
  [aux_sym_eqtex_sum_repeat1] = "eqtex_sum_repeat1",
  [aux_sym_eqtex_equations_repeat1] = "eqtex_equations_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__whitespace] = sym__whitespace,
  [sym_identifier] = sym_identifier,
  [sym_integer] = sym_integer,
  [sym_floating_point] = sym_floating_point,
  [anon_sym_AT] = anon_sym_AT,
  [sym_duration] = sym_duration,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym__] = anon_sym__,
  [anon_sym_DOLLAR_DOLLAR] = anon_sym_DOLLAR_DOLLAR,
  [sym_eqtex_text] = sym_eqtex_text,
  [sym_eqtex_number] = sym_eqtex_number,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_comment] = sym_comment,
  [sym_eol] = sym_eol,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym__number] = sym__number,
  [sym_enum_value] = sym_enum_value,
  [sym_variable] = sym_variable,
  [sym_command] = sym_command,
  [sym_environment_command] = sym_environment_command,
  [sym__argument] = sym__argument,
  [sym_eqtex] = sym_eqtex,
  [sym_eqtex_symbol] = sym_eqtex_symbol,
  [sym_eqtex_power] = sym_eqtex_power,
  [sym__eqtex_powerable] = sym__eqtex_powerable,
  [sym_eqtex_product] = sym_eqtex_product,
  [sym__eqtex_productable] = sym__eqtex_productable,
  [sym_eqtex_opposite] = sym_eqtex_opposite,
  [sym__eqtex_oppositable] = sym__eqtex_oppositable,
  [sym_eqtex_sum] = sym_eqtex_sum,
  [sym_eqtex_brackets] = sym_eqtex_brackets,
  [sym_eqtex_equations] = sym_eqtex_equations,
  [sym__eqtex_equationable] = sym__eqtex_equationable,
  [sym__eqtex_expression] = sym__eqtex_expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_command_repeat1] = aux_sym_command_repeat1,
  [aux_sym_eqtex_product_repeat1] = aux_sym_eqtex_product_repeat1,
  [aux_sym_eqtex_sum_repeat1] = aux_sym_eqtex_sum_repeat1,
  [aux_sym_eqtex_equations_repeat1] = aux_sym_eqtex_equations_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__whitespace] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_floating_point] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_duration] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_eqtex_text] = {
    .visible = true,
    .named = true,
  },
  [sym_eqtex_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_eol] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__number] = {
    .visible = false,
    .named = true,
  },
  [sym_enum_value] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_environment_command] = {
    .visible = true,
    .named = true,
  },
  [sym__argument] = {
    .visible = false,
    .named = true,
  },
  [sym_eqtex] = {
    .visible = true,
    .named = true,
  },
  [sym_eqtex_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_eqtex_power] = {
    .visible = true,
    .named = true,
  },
  [sym__eqtex_powerable] = {
    .visible = false,
    .named = true,
  },
  [sym_eqtex_product] = {
    .visible = true,
    .named = true,
  },
  [sym__eqtex_productable] = {
    .visible = false,
    .named = true,
  },
  [sym_eqtex_opposite] = {
    .visible = true,
    .named = true,
  },
  [sym__eqtex_oppositable] = {
    .visible = false,
    .named = true,
  },
  [sym_eqtex_sum] = {
    .visible = true,
    .named = true,
  },
  [sym_eqtex_brackets] = {
    .visible = true,
    .named = true,
  },
  [sym_eqtex_equations] = {
    .visible = true,
    .named = true,
  },
  [sym__eqtex_equationable] = {
    .visible = false,
    .named = true,
  },
  [sym__eqtex_expression] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_command_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_eqtex_product_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_eqtex_sum_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_eqtex_equations_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_argument = 1,
  field_duration = 2,
  field_id = 3,
  field_runtime = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_duration] = "duration",
  [field_id] = "id",
  [field_runtime] = "runtime",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 2},
  [9] = {.index = 13, .length = 3},
  [10] = {.index = 16, .length = 3},
  [11] = {.index = 19, .length = 3},
  [12] = {.index = 22, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_id, 0},
  [1] =
    {field_argument, 0},
  [2] =
    {field_id, 1},
  [3] =
    {field_duration, 1},
    {field_id, 0},
  [5] =
    {field_argument, 2, .inherited = true},
    {field_id, 0},
  [7] =
    {field_argument, 0, .inherited = true},
    {field_argument, 1, .inherited = true},
  [9] =
    {field_id, 0},
    {field_runtime, 1},
  [11] =
    {field_argument, 2, .inherited = true},
    {field_id, 1},
  [13] =
    {field_argument, 3, .inherited = true},
    {field_duration, 1},
    {field_id, 0},
  [16] =
    {field_duration, 1},
    {field_id, 0},
    {field_runtime, 2},
  [19] =
    {field_argument, 3, .inherited = true},
    {field_id, 0},
    {field_runtime, 1},
  [22] =
    {field_argument, 4, .inherited = true},
    {field_duration, 1},
    {field_id, 0},
    {field_runtime, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 39,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 77,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      if (lookahead == '$') ADVANCE(2);
      if (lookahead == '(') ADVANCE(45);
      if (lookahead == ')') ADVANCE(46);
      if (lookahead == '*') ADVANCE(30);
      if (lookahead == '+') ADVANCE(44);
      if (lookahead == '-') ADVANCE(43);
      if (lookahead == ';') ADVANCE(31);
      if (lookahead == '=') ADVANCE(49);
      if (lookahead == '@') ADVANCE(24);
      if (lookahead == '[') ADVANCE(47);
      if (lookahead == ']') ADVANCE(48);
      if (lookahead == '^') ADVANCE(39);
      if (lookahead == '_') ADVANCE(32);
      if (lookahead == '{') ADVANCE(40);
      if (lookahead == '}') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 1:
      if (lookahead == '$') ADVANCE(2);
      if (lookahead == '(') ADVANCE(45);
      if (lookahead == ')') ADVANCE(46);
      if (lookahead == '+') ADVANCE(44);
      if (lookahead == '-') ADVANCE(43);
      if (lookahead == '=') ADVANCE(49);
      if (lookahead == '[') ADVANCE(47);
      if (lookahead == ']') ADVANCE(48);
      if (lookahead == '^') ADVANCE(39);
      if (lookahead == '}') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 2:
      if (lookahead == '$') ADVANCE(33);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(30);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == ';') ADVANCE(31);
      if (lookahead == '@') ADVANCE(24);
      if (lookahead == '[') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(5);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '[') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == ']') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 7:
      if (lookahead == 'm') ADVANCE(26);
      if (lookahead == 's') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == '$') ADVANCE(2);
      if (lookahead == ')') ADVANCE(46);
      if (lookahead == '*') ADVANCE(30);
      if (lookahead == '+') ADVANCE(44);
      if (lookahead == '-') ADVANCE(42);
      if (lookahead == ';') ADVANCE(31);
      if (lookahead == '=') ADVANCE(49);
      if (lookahead == ']') ADVANCE(48);
      if (lookahead == '_') ADVANCE(32);
      if (lookahead == '}') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym__whitespace);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_floating_point);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == 'm') ADVANCE(26);
      if (lookahead == 's') ADVANCE(28);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_floating_point);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_floating_point);
      if (lookahead == '.') ADVANCE(13);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_floating_point);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_duration);
      if (lookahead == '_') ADVANCE(29);
      if (lookahead == 's') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_duration);
      if (lookahead == '_') ADVANCE(29);
      if (lookahead == 's') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_duration);
      if (lookahead == '_') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_duration);
      if (lookahead == '_') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_duration);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DOLLAR_DOLLAR);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_eqtex_text);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_eqtex_number);
      if (lookahead == 'm') ADVANCE(25);
      if (lookahead == 's') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_eqtex_number);
      if (lookahead == 'm') ADVANCE(26);
      if (lookahead == 's') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_eqtex_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_eqtex_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 14, .external_lex_state = 2},
  [2] = {.lex_state = 1, .external_lex_state = 2},
  [3] = {.lex_state = 1, .external_lex_state = 2},
  [4] = {.lex_state = 1, .external_lex_state = 2},
  [5] = {.lex_state = 1, .external_lex_state = 2},
  [6] = {.lex_state = 1, .external_lex_state = 2},
  [7] = {.lex_state = 1, .external_lex_state = 2},
  [8] = {.lex_state = 1, .external_lex_state = 2},
  [9] = {.lex_state = 3, .external_lex_state = 3},
  [10] = {.lex_state = 3, .external_lex_state = 3},
  [11] = {.lex_state = 3, .external_lex_state = 3},
  [12] = {.lex_state = 1, .external_lex_state = 2},
  [13] = {.lex_state = 1, .external_lex_state = 2},
  [14] = {.lex_state = 3, .external_lex_state = 3},
  [15] = {.lex_state = 3, .external_lex_state = 3},
  [16] = {.lex_state = 1, .external_lex_state = 2},
  [17] = {.lex_state = 1, .external_lex_state = 2},
  [18] = {.lex_state = 3, .external_lex_state = 3},
  [19] = {.lex_state = 1, .external_lex_state = 2},
  [20] = {.lex_state = 1, .external_lex_state = 2},
  [21] = {.lex_state = 3, .external_lex_state = 3},
  [22] = {.lex_state = 3, .external_lex_state = 3},
  [23] = {.lex_state = 3, .external_lex_state = 3},
  [24] = {.lex_state = 3, .external_lex_state = 3},
  [25] = {.lex_state = 3, .external_lex_state = 3},
  [26] = {.lex_state = 1, .external_lex_state = 2},
  [27] = {.lex_state = 1, .external_lex_state = 2},
  [28] = {.lex_state = 1, .external_lex_state = 2},
  [29] = {.lex_state = 1, .external_lex_state = 2},
  [30] = {.lex_state = 1, .external_lex_state = 2},
  [31] = {.lex_state = 1, .external_lex_state = 2},
  [32] = {.lex_state = 1, .external_lex_state = 2},
  [33] = {.lex_state = 14, .external_lex_state = 2},
  [34] = {.lex_state = 14, .external_lex_state = 2},
  [35] = {.lex_state = 14, .external_lex_state = 2},
  [36] = {.lex_state = 14, .external_lex_state = 2},
  [37] = {.lex_state = 14, .external_lex_state = 2},
  [38] = {.lex_state = 14, .external_lex_state = 2},
  [39] = {.lex_state = 3, .external_lex_state = 3},
  [40] = {.lex_state = 3, .external_lex_state = 3},
  [41] = {.lex_state = 14, .external_lex_state = 2},
  [42] = {.lex_state = 14, .external_lex_state = 2},
  [43] = {.lex_state = 14, .external_lex_state = 2},
  [44] = {.lex_state = 3, .external_lex_state = 3},
  [45] = {.lex_state = 14, .external_lex_state = 2},
  [46] = {.lex_state = 0, .external_lex_state = 2},
  [47] = {.lex_state = 0, .external_lex_state = 2},
  [48] = {.lex_state = 0, .external_lex_state = 2},
  [49] = {.lex_state = 0, .external_lex_state = 2},
  [50] = {.lex_state = 14, .external_lex_state = 2},
  [51] = {.lex_state = 14, .external_lex_state = 2},
  [52] = {.lex_state = 14, .external_lex_state = 2},
  [53] = {.lex_state = 14, .external_lex_state = 2},
  [54] = {.lex_state = 14, .external_lex_state = 2},
  [55] = {.lex_state = 14, .external_lex_state = 2},
  [56] = {.lex_state = 14, .external_lex_state = 2},
  [57] = {.lex_state = 14, .external_lex_state = 2},
  [58] = {.lex_state = 14, .external_lex_state = 2},
  [59] = {.lex_state = 14, .external_lex_state = 2},
  [60] = {.lex_state = 14, .external_lex_state = 2},
  [61] = {.lex_state = 14, .external_lex_state = 2},
  [62] = {.lex_state = 14, .external_lex_state = 2},
  [63] = {.lex_state = 14, .external_lex_state = 2},
  [64] = {.lex_state = 14, .external_lex_state = 2},
  [65] = {.lex_state = 14, .external_lex_state = 2},
  [66] = {.lex_state = 14, .external_lex_state = 2},
  [67] = {.lex_state = 14, .external_lex_state = 2},
  [68] = {.lex_state = 0, .external_lex_state = 2},
  [69] = {.lex_state = 0, .external_lex_state = 2},
  [70] = {.lex_state = 0, .external_lex_state = 2},
  [71] = {.lex_state = 0, .external_lex_state = 2},
  [72] = {.lex_state = 0, .external_lex_state = 2},
  [73] = {.lex_state = 0, .external_lex_state = 2},
  [74] = {.lex_state = 0, .external_lex_state = 2},
  [75] = {.lex_state = 0, .external_lex_state = 2},
  [76] = {.lex_state = 0, .external_lex_state = 2},
  [77] = {.lex_state = 14, .external_lex_state = 2},
  [78] = {.lex_state = 0, .external_lex_state = 2},
  [79] = {.lex_state = 0, .external_lex_state = 2},
  [80] = {.lex_state = 0, .external_lex_state = 2},
  [81] = {.lex_state = 14, .external_lex_state = 2},
  [82] = {.lex_state = 14, .external_lex_state = 2},
  [83] = {.lex_state = 14, .external_lex_state = 2},
};

enum {
  ts_external_token_comment = 0,
  ts_external_token_eol = 1,
  ts_external_token__newline = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_comment] = sym_comment,
  [ts_external_token_eol] = sym_eol,
  [ts_external_token__newline] = sym__newline,
};

static const bool ts_external_scanner_states[4][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_comment] = true,
    [ts_external_token_eol] = true,
    [ts_external_token__newline] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
  },
  [3] = {
    [ts_external_token_eol] = true,
    [ts_external_token__newline] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__whitespace] = ACTIONS(3),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [sym_duration] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_DOLLAR_DOLLAR] = ACTIONS(1),
    [sym_eqtex_text] = ACTIONS(1),
    [sym_eqtex_number] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_eol] = ACTIONS(1),
    [sym__newline] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(75),
    [sym__statement] = STATE(36),
    [sym_command] = STATE(36),
    [sym_environment_command] = STATE(36),
    [sym_eqtex] = STATE(36),
    [aux_sym_source_file_repeat1] = STATE(36),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym__whitespace] = ACTIONS(3),
    [sym_identifier] = ACTIONS(7),
    [anon_sym__] = ACTIONS(9),
    [anon_sym_DOLLAR_DOLLAR] = ACTIONS(11),
    [sym__newline] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    STATE(29), 1,
      sym_eqtex_power,
    STATE(32), 1,
      sym__eqtex_productable,
    STATE(33), 1,
      sym_eqtex_opposite,
    STATE(45), 1,
      sym_eqtex_product,
    STATE(49), 1,
      sym_eqtex_sum,
    STATE(56), 1,
      sym__eqtex_oppositable,
    STATE(69), 1,
      sym__eqtex_equationable,
    STATE(80), 1,
      sym__eqtex_powerable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(13), 2,
      sym_eqtex_text,
      sym_eqtex_number,
    STATE(16), 2,
      sym_eqtex_symbol,
      sym_eqtex_brackets,
    STATE(78), 2,
      sym_eqtex_equations,
      sym__eqtex_expression,
  [50] = 9,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_DASH,
    STATE(80), 1,
      sym__eqtex_powerable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(13), 2,
      sym_eqtex_text,
      sym_eqtex_number,
    STATE(17), 2,
      sym_eqtex_symbol,
      sym_eqtex_brackets,
    STATE(7), 3,
      sym_eqtex_power,
      sym__eqtex_productable,
      aux_sym_eqtex_product_repeat1,
    ACTIONS(21), 6,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [88] = 15,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    STATE(29), 1,
      sym_eqtex_power,
    STATE(32), 1,
      sym__eqtex_productable,
    STATE(33), 1,
      sym_eqtex_opposite,
    STATE(45), 1,
      sym_eqtex_product,
    STATE(49), 1,
      sym_eqtex_sum,
    STATE(56), 1,
      sym__eqtex_oppositable,
    STATE(69), 1,
      sym__eqtex_equationable,
    STATE(80), 1,
      sym__eqtex_powerable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(13), 2,
      sym_eqtex_text,
      sym_eqtex_number,
    STATE(16), 2,
      sym_eqtex_symbol,
      sym_eqtex_brackets,
    STATE(74), 2,
      sym_eqtex_equations,
      sym__eqtex_expression,
  [138] = 15,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    STATE(29), 1,
      sym_eqtex_power,
    STATE(32), 1,
      sym__eqtex_productable,
    STATE(33), 1,
      sym_eqtex_opposite,
    STATE(45), 1,
      sym_eqtex_product,
    STATE(49), 1,
      sym_eqtex_sum,
    STATE(56), 1,
      sym__eqtex_oppositable,
    STATE(69), 1,
      sym__eqtex_equationable,
    STATE(80), 1,
      sym__eqtex_powerable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(13), 2,
      sym_eqtex_text,
      sym_eqtex_number,
    STATE(16), 2,
      sym_eqtex_symbol,
      sym_eqtex_brackets,
    STATE(70), 2,
      sym_eqtex_equations,
      sym__eqtex_expression,
  [188] = 15,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    STATE(29), 1,
      sym_eqtex_power,
    STATE(32), 1,
      sym__eqtex_productable,
    STATE(33), 1,
      sym_eqtex_opposite,
    STATE(45), 1,
      sym_eqtex_product,
    STATE(49), 1,
      sym_eqtex_sum,
    STATE(56), 1,
      sym__eqtex_oppositable,
    STATE(69), 1,
      sym__eqtex_equationable,
    STATE(80), 1,
      sym__eqtex_powerable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(13), 2,
      sym_eqtex_text,
      sym_eqtex_number,
    STATE(16), 2,
      sym_eqtex_symbol,
      sym_eqtex_brackets,
    STATE(73), 2,
      sym_eqtex_equations,
      sym__eqtex_expression,
  [238] = 9,
    ACTIONS(30), 1,
      anon_sym_DASH,
    ACTIONS(32), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_LBRACK,
    STATE(80), 1,
      sym__eqtex_powerable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(27), 2,
      sym_eqtex_text,
      sym_eqtex_number,
    STATE(17), 2,
      sym_eqtex_symbol,
      sym_eqtex_brackets,
    STATE(7), 3,
      sym_eqtex_power,
      sym__eqtex_productable,
      aux_sym_eqtex_product_repeat1,
    ACTIONS(25), 6,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [276] = 13,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    STATE(26), 1,
      sym_eqtex_power,
    STATE(32), 1,
      sym__eqtex_productable,
    STATE(35), 1,
      sym_eqtex_opposite,
    STATE(41), 1,
      sym_eqtex_product,
    STATE(56), 1,
      sym__eqtex_oppositable,
    STATE(80), 1,
      sym__eqtex_powerable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(13), 2,
      sym_eqtex_text,
      sym_eqtex_number,
    STATE(20), 2,
      sym_eqtex_symbol,
      sym_eqtex_brackets,
    STATE(48), 2,
      sym_eqtex_sum,
      sym__eqtex_equationable,
  [320] = 8,
    ACTIONS(40), 1,
      sym_floating_point,
    ACTIONS(42), 1,
      anon_sym_AT,
    ACTIONS(44), 1,
      anon_sym_STAR,
    STATE(23), 1,
      aux_sym_command_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(38), 2,
      sym_integer,
      sym_duration,
    ACTIONS(46), 2,
      sym_eol,
      anon_sym_SEMI,
    STATE(40), 4,
      sym__number,
      sym_enum_value,
      sym_variable,
      sym__argument,
  [351] = 9,
    ACTIONS(40), 1,
      sym_floating_point,
    ACTIONS(42), 1,
      anon_sym_AT,
    ACTIONS(44), 1,
      anon_sym_STAR,
    ACTIONS(48), 1,
      anon_sym_SEMI,
    ACTIONS(50), 1,
      sym_eol,
    STATE(25), 1,
      aux_sym_command_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(38), 2,
      sym_integer,
      sym_duration,
    STATE(40), 4,
      sym__number,
      sym_enum_value,
      sym_variable,
      sym__argument,
  [384] = 8,
    ACTIONS(40), 1,
      sym_floating_point,
    ACTIONS(42), 1,
      anon_sym_AT,
    ACTIONS(44), 1,
      anon_sym_STAR,
    STATE(14), 1,
      aux_sym_command_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(38), 2,
      sym_integer,
      sym_duration,
    ACTIONS(52), 2,
      sym_eol,
      anon_sym_SEMI,
    STATE(40), 4,
      sym__number,
      sym_enum_value,
      sym_variable,
      sym__argument,
  [415] = 3,
    ACTIONS(56), 1,
      anon_sym_DASH,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(54), 11,
      anon_sym_DOLLAR_DOLLAR,
      sym_eqtex_text,
      sym_eqtex_number,
      anon_sym_CARET,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [436] = 5,
    ACTIONS(62), 1,
      anon_sym_CARET,
    ACTIONS(64), 1,
      anon_sym_DASH,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(60), 4,
      sym_eqtex_text,
      sym_eqtex_number,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
    ACTIONS(58), 6,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [461] = 9,
    ACTIONS(40), 1,
      sym_floating_point,
    ACTIONS(42), 1,
      anon_sym_AT,
    ACTIONS(44), 1,
      anon_sym_STAR,
    ACTIONS(66), 1,
      anon_sym_SEMI,
    ACTIONS(68), 1,
      sym_eol,
    STATE(25), 1,
      aux_sym_command_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(38), 2,
      sym_integer,
      sym_duration,
    STATE(40), 4,
      sym__number,
      sym_enum_value,
      sym_variable,
      sym__argument,
  [494] = 8,
    ACTIONS(40), 1,
      sym_floating_point,
    ACTIONS(42), 1,
      anon_sym_AT,
    ACTIONS(44), 1,
      anon_sym_STAR,
    STATE(18), 1,
      aux_sym_command_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(38), 2,
      sym_integer,
      sym_duration,
    ACTIONS(70), 2,
      sym_eol,
      anon_sym_SEMI,
    STATE(40), 4,
      sym__number,
      sym_enum_value,
      sym_variable,
      sym__argument,
  [525] = 7,
    ACTIONS(58), 1,
      anon_sym_PLUS,
    ACTIONS(62), 1,
      anon_sym_CARET,
    ACTIONS(64), 1,
      anon_sym_DASH,
    ACTIONS(74), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(60), 4,
      sym_eqtex_text,
      sym_eqtex_number,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
    ACTIONS(72), 4,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [554] = 4,
    ACTIONS(62), 1,
      anon_sym_CARET,
    ACTIONS(76), 1,
      anon_sym_DASH,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(60), 10,
      anon_sym_DOLLAR_DOLLAR,
      sym_eqtex_text,
      sym_eqtex_number,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [577] = 9,
    ACTIONS(40), 1,
      sym_floating_point,
    ACTIONS(42), 1,
      anon_sym_AT,
    ACTIONS(44), 1,
      anon_sym_STAR,
    ACTIONS(78), 1,
      anon_sym_SEMI,
    ACTIONS(80), 1,
      sym_eol,
    STATE(25), 1,
      aux_sym_command_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(38), 2,
      sym_integer,
      sym_duration,
    STATE(40), 4,
      sym__number,
      sym_enum_value,
      sym_variable,
      sym__argument,
  [610] = 3,
    ACTIONS(84), 1,
      anon_sym_DASH,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(82), 11,
      anon_sym_DOLLAR_DOLLAR,
      sym_eqtex_text,
      sym_eqtex_number,
      anon_sym_CARET,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [631] = 6,
    ACTIONS(58), 1,
      anon_sym_PLUS,
    ACTIONS(62), 1,
      anon_sym_CARET,
    ACTIONS(64), 1,
      anon_sym_DASH,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(60), 4,
      sym_eqtex_text,
      sym_eqtex_number,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
    ACTIONS(74), 5,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [658] = 8,
    ACTIONS(40), 1,
      sym_floating_point,
    ACTIONS(42), 1,
      anon_sym_AT,
    ACTIONS(44), 1,
      anon_sym_STAR,
    STATE(24), 1,
      aux_sym_command_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(38), 2,
      sym_integer,
      sym_duration,
    ACTIONS(86), 2,
      sym_eol,
      anon_sym_SEMI,
    STATE(40), 4,
      sym__number,
      sym_enum_value,
      sym_variable,
      sym__argument,
  [689] = 8,
    ACTIONS(40), 1,
      sym_floating_point,
    ACTIONS(42), 1,
      anon_sym_AT,
    ACTIONS(44), 1,
      anon_sym_STAR,
    STATE(10), 1,
      aux_sym_command_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(38), 2,
      sym_integer,
      sym_duration,
    ACTIONS(88), 2,
      sym_eol,
      anon_sym_SEMI,
    STATE(40), 4,
      sym__number,
      sym_enum_value,
      sym_variable,
      sym__argument,
  [720] = 9,
    ACTIONS(40), 1,
      sym_floating_point,
    ACTIONS(42), 1,
      anon_sym_AT,
    ACTIONS(44), 1,
      anon_sym_STAR,
    ACTIONS(90), 1,
      anon_sym_SEMI,
    ACTIONS(92), 1,
      sym_eol,
    STATE(25), 1,
      aux_sym_command_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(38), 2,
      sym_integer,
      sym_duration,
    STATE(40), 4,
      sym__number,
      sym_enum_value,
      sym_variable,
      sym__argument,
  [753] = 9,
    ACTIONS(40), 1,
      sym_floating_point,
    ACTIONS(42), 1,
      anon_sym_AT,
    ACTIONS(44), 1,
      anon_sym_STAR,
    ACTIONS(94), 1,
      anon_sym_SEMI,
    ACTIONS(96), 1,
      sym_eol,
    STATE(25), 1,
      aux_sym_command_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(38), 2,
      sym_integer,
      sym_duration,
    STATE(40), 4,
      sym__number,
      sym_enum_value,
      sym_variable,
      sym__argument,
  [786] = 8,
    ACTIONS(101), 1,
      sym_floating_point,
    ACTIONS(104), 1,
      anon_sym_AT,
    ACTIONS(107), 1,
      anon_sym_STAR,
    STATE(25), 1,
      aux_sym_command_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(98), 2,
      sym_integer,
      sym_duration,
    ACTIONS(110), 2,
      sym_eol,
      anon_sym_SEMI,
    STATE(40), 4,
      sym__number,
      sym_enum_value,
      sym_variable,
      sym__argument,
  [817] = 5,
    ACTIONS(58), 1,
      anon_sym_PLUS,
    ACTIONS(64), 1,
      anon_sym_DASH,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(60), 4,
      sym_eqtex_text,
      sym_eqtex_number,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
    ACTIONS(74), 5,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [841] = 9,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    STATE(30), 1,
      sym_eqtex_power,
    STATE(32), 1,
      sym__eqtex_productable,
    STATE(80), 1,
      sym__eqtex_powerable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(13), 2,
      sym_eqtex_text,
      sym_eqtex_number,
    STATE(13), 2,
      sym_eqtex_symbol,
      sym_eqtex_brackets,
    STATE(42), 2,
      sym_eqtex_product,
      sym__eqtex_oppositable,
  [873] = 9,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    STATE(30), 1,
      sym_eqtex_power,
    STATE(32), 1,
      sym__eqtex_productable,
    STATE(80), 1,
      sym__eqtex_powerable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(13), 2,
      sym_eqtex_text,
      sym_eqtex_number,
    STATE(13), 2,
      sym_eqtex_symbol,
      sym_eqtex_brackets,
    STATE(43), 2,
      sym_eqtex_product,
      sym__eqtex_oppositable,
  [905] = 6,
    ACTIONS(58), 1,
      anon_sym_PLUS,
    ACTIONS(64), 1,
      anon_sym_DASH,
    ACTIONS(74), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(60), 4,
      sym_eqtex_text,
      sym_eqtex_number,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
    ACTIONS(72), 4,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [931] = 4,
    ACTIONS(64), 1,
      anon_sym_DASH,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(60), 4,
      sym_eqtex_text,
      sym_eqtex_number,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
    ACTIONS(58), 6,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [953] = 3,
    ACTIONS(114), 1,
      anon_sym_DASH,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(112), 10,
      anon_sym_DOLLAR_DOLLAR,
      sym_eqtex_text,
      sym_eqtex_number,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [973] = 7,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    STATE(80), 1,
      sym__eqtex_powerable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(13), 2,
      sym_eqtex_text,
      sym_eqtex_number,
    STATE(17), 2,
      sym_eqtex_symbol,
      sym_eqtex_brackets,
    STATE(3), 3,
      sym_eqtex_power,
      sym__eqtex_productable,
      aux_sym_eqtex_product_repeat1,
  [1000] = 6,
    ACTIONS(74), 1,
      anon_sym_EQ,
    ACTIONS(116), 1,
      anon_sym_DASH,
    ACTIONS(118), 1,
      anon_sym_PLUS,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    STATE(34), 2,
      sym_eqtex_opposite,
      aux_sym_eqtex_sum_repeat1,
    ACTIONS(72), 4,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1024] = 5,
    ACTIONS(116), 1,
      anon_sym_DASH,
    ACTIONS(118), 1,
      anon_sym_PLUS,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    STATE(37), 2,
      sym_eqtex_opposite,
      aux_sym_eqtex_sum_repeat1,
    ACTIONS(120), 5,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [1046] = 5,
    ACTIONS(116), 1,
      anon_sym_DASH,
    ACTIONS(118), 1,
      anon_sym_PLUS,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    STATE(34), 2,
      sym_eqtex_opposite,
      aux_sym_eqtex_sum_repeat1,
    ACTIONS(74), 5,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [1068] = 6,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym__,
    ACTIONS(11), 1,
      anon_sym_DOLLAR_DOLLAR,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    STATE(38), 5,
      sym__statement,
      sym_command,
      sym_environment_command,
      sym_eqtex,
      aux_sym_source_file_repeat1,
  [1092] = 5,
    ACTIONS(126), 1,
      anon_sym_DASH,
    ACTIONS(129), 1,
      anon_sym_PLUS,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    STATE(37), 2,
      sym_eqtex_opposite,
      aux_sym_eqtex_sum_repeat1,
    ACTIONS(124), 5,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [1114] = 6,
    ACTIONS(132), 1,
      ts_builtin_sym_end,
    ACTIONS(134), 1,
      sym_identifier,
    ACTIONS(137), 1,
      anon_sym__,
    ACTIONS(140), 1,
      anon_sym_DOLLAR_DOLLAR,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    STATE(38), 5,
      sym__statement,
      sym_command,
      sym_environment_command,
      sym_eqtex,
      aux_sym_source_file_repeat1,
  [1138] = 3,
    ACTIONS(145), 1,
      sym_floating_point,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(143), 6,
      sym_eol,
      sym_integer,
      anon_sym_AT,
      sym_duration,
      anon_sym_STAR,
      anon_sym_SEMI,
  [1154] = 3,
    ACTIONS(149), 1,
      sym_floating_point,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(147), 6,
      sym_eol,
      sym_integer,
      anon_sym_AT,
      sym_duration,
      anon_sym_STAR,
      anon_sym_SEMI,
  [1170] = 3,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(58), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(74), 5,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [1186] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(151), 7,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [1200] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(124), 7,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [1214] = 3,
    ACTIONS(155), 1,
      sym_floating_point,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(153), 6,
      sym_eol,
      sym_integer,
      anon_sym_AT,
      sym_duration,
      anon_sym_STAR,
      anon_sym_SEMI,
  [1230] = 4,
    ACTIONS(74), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(58), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(72), 4,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1248] = 4,
    ACTIONS(159), 1,
      anon_sym_EQ,
    STATE(46), 1,
      aux_sym_eqtex_equations_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(157), 4,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1265] = 4,
    ACTIONS(164), 1,
      anon_sym_EQ,
    STATE(46), 1,
      aux_sym_eqtex_equations_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(162), 4,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1282] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(157), 5,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_EQ,
  [1294] = 3,
    ACTIONS(74), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(72), 4,
      anon_sym_DOLLAR_DOLLAR,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1308] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(166), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1319] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(168), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1330] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(170), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1341] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(172), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1352] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(174), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1363] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(174), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1374] = 4,
    ACTIONS(116), 1,
      anon_sym_DASH,
    ACTIONS(118), 1,
      anon_sym_PLUS,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    STATE(34), 2,
      sym_eqtex_opposite,
      aux_sym_eqtex_sum_repeat1,
  [1389] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(176), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1400] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(178), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1411] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(180), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1422] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(180), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1433] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(182), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1444] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(182), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1455] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(184), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1466] = 5,
    ACTIONS(186), 1,
      sym_duration,
    ACTIONS(188), 1,
      anon_sym_STAR,
    ACTIONS(190), 1,
      anon_sym_SEMI,
    STATE(79), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [1483] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(168), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1494] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(178), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1505] = 2,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
    ACTIONS(192), 4,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym__,
      anon_sym_DOLLAR_DOLLAR,
  [1516] = 4,
    ACTIONS(188), 1,
      anon_sym_STAR,
    ACTIONS(194), 1,
      anon_sym_SEMI,
    STATE(72), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [1530] = 3,
    ACTIONS(164), 1,
      anon_sym_EQ,
    STATE(47), 1,
      aux_sym_eqtex_equations_repeat1,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [1541] = 2,
    ACTIONS(196), 1,
      anon_sym_RBRACK,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [1549] = 2,
    ACTIONS(143), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [1557] = 2,
    ACTIONS(198), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [1565] = 2,
    ACTIONS(196), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [1573] = 2,
    ACTIONS(200), 1,
      anon_sym_DOLLAR_DOLLAR,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [1581] = 2,
    ACTIONS(202), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [1589] = 2,
    ACTIONS(204), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [1597] = 2,
    ACTIONS(206), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [1605] = 2,
    ACTIONS(208), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [1613] = 2,
    ACTIONS(210), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [1621] = 2,
    ACTIONS(212), 1,
      anon_sym_CARET,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [1629] = 2,
    ACTIONS(214), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [1637] = 2,
    ACTIONS(216), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
  [1645] = 2,
    ACTIONS(218), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym__newline,
      sym__whitespace,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 50,
  [SMALL_STATE(4)] = 88,
  [SMALL_STATE(5)] = 138,
  [SMALL_STATE(6)] = 188,
  [SMALL_STATE(7)] = 238,
  [SMALL_STATE(8)] = 276,
  [SMALL_STATE(9)] = 320,
  [SMALL_STATE(10)] = 351,
  [SMALL_STATE(11)] = 384,
  [SMALL_STATE(12)] = 415,
  [SMALL_STATE(13)] = 436,
  [SMALL_STATE(14)] = 461,
  [SMALL_STATE(15)] = 494,
  [SMALL_STATE(16)] = 525,
  [SMALL_STATE(17)] = 554,
  [SMALL_STATE(18)] = 577,
  [SMALL_STATE(19)] = 610,
  [SMALL_STATE(20)] = 631,
  [SMALL_STATE(21)] = 658,
  [SMALL_STATE(22)] = 689,
  [SMALL_STATE(23)] = 720,
  [SMALL_STATE(24)] = 753,
  [SMALL_STATE(25)] = 786,
  [SMALL_STATE(26)] = 817,
  [SMALL_STATE(27)] = 841,
  [SMALL_STATE(28)] = 873,
  [SMALL_STATE(29)] = 905,
  [SMALL_STATE(30)] = 931,
  [SMALL_STATE(31)] = 953,
  [SMALL_STATE(32)] = 973,
  [SMALL_STATE(33)] = 1000,
  [SMALL_STATE(34)] = 1024,
  [SMALL_STATE(35)] = 1046,
  [SMALL_STATE(36)] = 1068,
  [SMALL_STATE(37)] = 1092,
  [SMALL_STATE(38)] = 1114,
  [SMALL_STATE(39)] = 1138,
  [SMALL_STATE(40)] = 1154,
  [SMALL_STATE(41)] = 1170,
  [SMALL_STATE(42)] = 1186,
  [SMALL_STATE(43)] = 1200,
  [SMALL_STATE(44)] = 1214,
  [SMALL_STATE(45)] = 1230,
  [SMALL_STATE(46)] = 1248,
  [SMALL_STATE(47)] = 1265,
  [SMALL_STATE(48)] = 1282,
  [SMALL_STATE(49)] = 1294,
  [SMALL_STATE(50)] = 1308,
  [SMALL_STATE(51)] = 1319,
  [SMALL_STATE(52)] = 1330,
  [SMALL_STATE(53)] = 1341,
  [SMALL_STATE(54)] = 1352,
  [SMALL_STATE(55)] = 1363,
  [SMALL_STATE(56)] = 1374,
  [SMALL_STATE(57)] = 1389,
  [SMALL_STATE(58)] = 1400,
  [SMALL_STATE(59)] = 1411,
  [SMALL_STATE(60)] = 1422,
  [SMALL_STATE(61)] = 1433,
  [SMALL_STATE(62)] = 1444,
  [SMALL_STATE(63)] = 1455,
  [SMALL_STATE(64)] = 1466,
  [SMALL_STATE(65)] = 1483,
  [SMALL_STATE(66)] = 1494,
  [SMALL_STATE(67)] = 1505,
  [SMALL_STATE(68)] = 1516,
  [SMALL_STATE(69)] = 1530,
  [SMALL_STATE(70)] = 1541,
  [SMALL_STATE(71)] = 1549,
  [SMALL_STATE(72)] = 1557,
  [SMALL_STATE(73)] = 1565,
  [SMALL_STATE(74)] = 1573,
  [SMALL_STATE(75)] = 1581,
  [SMALL_STATE(76)] = 1589,
  [SMALL_STATE(77)] = 1597,
  [SMALL_STATE(78)] = 1605,
  [SMALL_STATE(79)] = 1613,
  [SMALL_STATE(80)] = 1621,
  [SMALL_STATE(81)] = 1629,
  [SMALL_STATE(82)] = 1637,
  [SMALL_STATE(83)] = 1645,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eqtex_product, 2),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_eqtex_product, 2),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_eqtex_product_repeat1, 2),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_eqtex_product_repeat1, 2), SHIFT_REPEAT(12),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_eqtex_product_repeat1, 2),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_eqtex_product_repeat1, 2), SHIFT_REPEAT(6),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_eqtex_product_repeat1, 2), SHIFT_REPEAT(5),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eqtex_symbol, 1),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_eqtex_symbol, 1),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__eqtex_oppositable, 1),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__eqtex_productable, 1),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__eqtex_powerable, 1),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__eqtex_oppositable, 1),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__eqtex_expression, 1),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__eqtex_equationable, 1),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__eqtex_productable, 1),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eqtex_brackets, 3),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_eqtex_brackets, 3),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2, .production_id = 6), SHIFT_REPEAT(40),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, .production_id = 6), SHIFT_REPEAT(40),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2, .production_id = 6), SHIFT_REPEAT(82),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2, .production_id = 6), SHIFT_REPEAT(83),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2, .production_id = 6),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eqtex_power, 5),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_eqtex_power, 5),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eqtex_sum, 2),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_eqtex_sum_repeat1, 2),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_eqtex_sum_repeat1, 2), SHIFT_REPEAT(27),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_eqtex_sum_repeat1, 2), SHIFT_REPEAT(28),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(64),
  [137] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(81),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(4),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 2),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 2),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 1, .production_id = 2),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 1, .production_id = 2),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eqtex_opposite, 2),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_value, 2),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_enum_value, 2),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_eqtex_equations_repeat1, 2),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_eqtex_equations_repeat1, 2), SHIFT_REPEAT(8),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eqtex_equations, 2),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 5, .production_id = 10),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 5, .production_id = 9),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eqtex, 3),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 4, .production_id = 4),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 4, .production_id = 5),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 4, .production_id = 7),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_environment_command, 4, .production_id = 8),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 6, .production_id = 12),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 5, .production_id = 11),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 3, .production_id = 1),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_environment_command, 3, .production_id = 3),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [202] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_eqideo_external_scanner_create(void);
void tree_sitter_eqideo_external_scanner_destroy(void *);
bool tree_sitter_eqideo_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_eqideo_external_scanner_serialize(void *, char *);
void tree_sitter_eqideo_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_eqideo(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_eqideo_external_scanner_create,
      tree_sitter_eqideo_external_scanner_destroy,
      tree_sitter_eqideo_external_scanner_scan,
      tree_sitter_eqideo_external_scanner_serialize,
      tree_sitter_eqideo_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
